veliovgroup/Meteor-Files

docs/google-cloud-storage-integration.md

This time commiting to the correct branch. Fixed the one typo your pointed out and an error that caused my code to throw an error (I missed the r in one of the requires). I think there was one more error, but I honestly cannot remember what it was...I think it was a change I made to make the code suit my application. Needless to say, after correcting small errors, the code will indeed run.

Added docs for Google Cloud Storage

---

demo/app.json
demo/package.json
docs/aws-s3-integration.md

- Docs update for AWS:S3 integration, see #174 
- Demo App: Version bump

Minor update

---

files.coffee

Reverts VeliovGroup/Meteor-Files#185
Should be merged to `dev` branch

Revert "fix to get extension if link has query params after extension"

---

docs/google-cloud-storage-integration.md

**ISSUES:**
1-gcloud-node official pacakge is now rename to google-cloud-node
2-No need to make file public (get file with bucket authentication and pipe it to meteor application user)

document enhance, and removed depreciate package

---

files.coffee

#210
I've conducted the following tests and confirmed that there is no inconsistency.

Refix #210

---

files.coffee
package.js

fixes https://github.com/VeliovGroup/Meteor-Files/issues/242

Template is now a weak depencency

---

docs/aws-s3-integration.md

As discussed in the issue. Now the documentation includes the CORS step.

Updated AWS S3 docs

---

files.coffee

Close #361.
Turned out to be even easier than I thought 😀

reapply type-detection logic during 'finish'

---

files.coffee

Fix #400 - Exception while adding files from server using .addFile()

Fix addfile() -> filename of undefined

---

docs/aws-s3-integration.md

I have updated the docs and removed knox and used the supported aws-sdk. Also have included some other security solutions to protected files.

updated the s3 example to use aws-sdk - supported

---

docs/image-processing.md

Added some starter information for IM and GM

---

docs/constructor.md

1. Make sure you're sending PR to `dev` branch
2. Give a short description what you have changed/added and why

cacheControle parameter information link

---

docs/google-cloud-storage-integration.md

Add missing var self = this; to interceptDownload

Update google cloud integration example

---

client.js
core.js
docs/constructor.md
docs/schema.md
server.js

Add static schema getter

---

client.js
docs/insert.md
upload.js

As mentioned in the previous PR ( from master ).
The purpose in to allow insert using a specific ID
- File is correctly indent.
- Where do i put the documentation about this ?

Allow id to be specified at insert

---

docs/constructor.md
server.js

Allow to pass _preCollection options

---

docs/react-example.md

Issue: https://github.com/VeliovGroup/Meteor-Files/issues/572

Edited React example to use Meteor 1.6.1, withTracker, React 15/16

---

docs/aws-s3-integration.md

Replace generic text with console logging of error

Correction of error handling

---

README.md
docs/react-native-example.md

Added reference to React Native demo repository to docs and readme

Add React Native demo repo reference

---

README.md
docs/react-native-example.md

Reverts VeliovGroup/Meteor-Files#652

Revert "Add React Native demo repo reference"

---

docs/aws-s3-integration.md

Adds hint about adapting the IAM policy so that files can be removed from S3.
Closes #658

Improve AWS S3 integration docs

---

docs/typescript-definitions.md
index.d.ts

- Add metadata and transformed type params.
- Fix TypeRef type.
- Replace 'Object' and 'any' types  where possible with specific types.
- Add /index.d.ts

Improve typescript definitions.

---

docs/typescript-definitions.md
index.d.ts

Okay so I think this is finally a complete and (at least more) correct set of TS defs. It matches the code examples, and is the result of a lot of digging in the code to check actual types of all function signatures, config objects, callback function arguments...

Complete typescript definitions.

---

docs/dropbox-integration.md

The current Dropbox storage integration is using the DropBox API v1, which is [deprecated since almost 4 years now](https://dropbox.tech/developers/api-v1-deprecated). 
Based on [the code provided in 2017 by Buom01](https://github.com/VeliovGroup/Meteor-Files/issues/112#issuecomment-281976126) [in a related issue](https://github.com/VeliovGroup/Meteor-Files/issues/112), I updated the docs about Dropbox storage integration with a code working with the latest packages & DropBox API.
As before, it covers how to store and serve uploaded file and how to remove it.
I did my best to get as close as possible to the syntax used before, and I tested the code without any problems under development & production.
This is my first pull request and I'm just a 17 yo hobbyist, as I said I did my best but …

DropBox storage integration updated for API v2
