veliovgroup/Meteor-Files

README.md
files.coffee

New feature satisfying my feature request: #56 
Like the title states, this adds a reactive state variable to the [upload instance object](https://github.com/VeliovGroup/Meteor-Files#insertsettings-client) returned by files.insert().  
It has four states:
* active - file is currently actively uploading
* paused - file upload is paused
* aborted - file upload has been aborted and can no longer be completed
* completed - file has been successfully uploaded
This is useful in easily maintaining consistent state, rather than having to infer it from a variety of factors.
I have not meddled in the existing `onPause` state variable, however `state` renders it redundant.  @dr-dimitru may want to update the package to replace `onPause` with `state` if this request is accepted.

Added reactive state property to the upload instance object returned by files.insert()

---

docs/constructor.md
files.coffee

This adds `chunkId` and `eof` as context for `onBeforeUpload` to help solving https://github.com/VeliovGroup/Meteor-Files/issues/79 
This is needed to determine if validation based on `meta` should fire. We need to know when to expect metadata since `meta`is transmitted on the first and last chunk only.

add context.chunkId and context.eof to onBeforeUpload

---

files.coffee

**Previous Behavior**
Previously getExt return the object with extension having any string after "."
**Now**
getExt will return ext in between '.' and '?' (so it trim the query params including question mark)
**Blocking Cause**
On Windows Special characters (which are found in query params '?' '&' ) are not allowed in file or folder naming convention therefore not allowing file stream to write. 
**Tested On**
Windows 10
This PR is raise again [this issue](https://github.com/VeliovGroup/Meteor-Files/issues/184)

fix to get extension if link has query params after extension

---

docs/google-cloud-storage-integration.md

Meteor sync function
`self.unlink(self.collection.findOne(fileRef._id), version); `
is not working as expected, as it was not bounded by Meteor.bindEnvironment function.
due to this, after successful uploading files to google cloud storage, files were not deleting from local app storage.
PR is raise against [this issue](https://github.com/VeliovGroup/Meteor-Files/issues/217)

fix google doc for meteor env

---

files.coffee

Fix #210 (the inconsistency of the behaviour of `find` and `findOne` between `Mongo.Collection` and `FilesCollection`)

Fix #210 again.

---

README.md
docs/constructor.md

In constructor.md, add clarification under `config.storagePath` for handling of files stored at a relative path when in development mode. Let me know what you think.

Doc update

---

docs/addFile.md
files.coffee

solves #298
Do we need to to set userId to null? Isn't it better to skip that (userId === undefined)?
*no expert in CoffeeScript, review advised*

be able to pass userId to addFile (API)

---

files.coffee

Though the call to Collection.update should be blocking (server side) according to metoer API:
https://docs.meteor.com/api/collections.html#Mongo-Collection-update
In fact the update sometimes is not completed before the remove kicks in, which in turn triggers the preCollection.obeserve("remove") code. This leads to the situation that the oberver code sees an unfinished upload while the upload actually finished correctly.

Delay the preCollection remove after upload to workaround sporadic timing issue. Fixes #324

---

docs/collection-instances.md
docs/toc.md

**Assumptions**
I assumed the attribute name of the reference to be `filesCollection` which makes the most sense in terms of self descriptiveness.
**Contribution**
- Added a general description of the reference chain
- Added a description for the use case with dburles:mongo-collection-instances
- Added a description for the use case with a custom instance map

Dev - Documentation added For Collection Instances

---

server.coffee

Sometimes the remote server is expecting some headers (like 'Authorization' or 'Accept') before it will serve your file. This PR allows users to supply a `headers` object to customize the headers sent with the HTTP request.
e.g.
```js
MyImages.load(url, {
headers: { Authorization: `Bearer ${user.accessToken}` },
}, (error, file) => ...);
```

Allow `headers` to be passed as an option to FilesCollection#load

---

core.js
docs/schema.md

I've found that validation fails on a document returned from a `FilesCollection` using the static schema because it's missing a few keys (`_id`, `ext`, `extenstionWithDot`, `mime`, `mime-type`)
Picked it up when directly importing my merged schema for validation of docs passed into a template. Confirmed it using `FilesCollection.schema` directly too.
This PR adds those missing keys to `FilesCollection.schema`

Fix validation errors when using `FilesCollection.schema` on a document

---

server.js

Occurs specially often when one server has a higher latency to the database.
Fixes #672

Fixed the auto-file-removal

---

docs/gridfs-migration.md
docs/toc.md

Related discussion: #686
This PR adds a tutorial to the documentation / wiki which describes how to move documents of a `FilesCollection` and GridFS related metadata `fs.files` and chunks `fs.chunks` between multiple instances of Meteor applications, which do not share a common database.
Code derived from an implementation that successfully migrates a whole FilesCollection from one app/db to another app2/db2 including preservation of ids.

Update docs for #686 Move GridFS Files/Chunks between DBs

---

server.js

- Changes were introduced in https://github.com/meteor/meteor/commit/79ae1849f5846e207ed4dfa49831ba409252fd03
- Without this, this project is incompatible with Meteor >= 1.8.1
- Meteor.server.sessions is a Map and not an Object anymore.
fixes https://github.com/VeliovGroup/Meteor-Files/issues/681

fixes getting the userId with the x-mtok from Meteor.server.sessions

---

.github/FUNDING.yml
upload.js

On progress, there is now available raw info about count of sent chunks, which should provide more accurate calculation of progress, discussed in #704.
On abort was called before state `aborted` was set which led to bugs, so this is fixed. Discussed in #706.

Progress info upgrade #704, abort event fix #706

---

client.js

@dr-dimitru 
My statement in https://github.com/VeliovGroup/Meteor-Files/issues/656#issuecomment-605661501 was wrong, I accidentally tested against the wrong branch, sorry for that. 🤦‍♂️
This PR fixes the following:
1. whitelists `allowQueryStringCookies`, otherwise it's just ignored.
2. `cookie.send();` is crucial here (and not obsolete), as this requests the server to set the cookie since just setting cookies on the client has no impact. This fulfills the reasoning around `allowQueryStringCookies`.
`cookie.send()` then results in 
when `setTokenCookie` is called.

Fix allow query string cookies

---

docs/typescript-definitions.md
index.d.ts

Sorry, realised later that I'd stuffed up how the types for the options.transform function in find and findOne functions was handled. See comments for find() and findOne() in the defs for more info...
- Fixes handling of types for options.transform function in find and findOne.
- Adds specific types to FilesCursor functions.

Fixes and improvements to typescript defs.

---

docs/aws-s3-integration.md

The Amazon S3 integration documentation shows an example of monkeypatching the `FilesCollection.remove` method but without forwarding a potential callback.

📔 Improve AWS S3 documentation

---

README.md
client.js

Meteor Community package [meteor-desktop](https://github.com/Meteor-Community-Packages/meteor-desktop) allows to build desktop apps with Meteor & Electron. As far as Meteor is concerned, it works like the Cordova integration, which it piggy-backs. The only needed change is that `Meteor.isCordova` is replaced by `Meteor.isDesktop`.
We have been used Meteor-Files & meteor-cookies in a meteor-desktop project, with the proposed code change, for a while without issue.

Make Meteor-Files compatible with meteor-desktop (#881)

---

docs/gridfs-bucket-integration.md

Hello this is a problem I ran into during our migration and I thought it'd be nice to document so others could avoid this pitfall.
First off, the internal API for objectId got changed. Meteor even caught on this and updated their [code](https://github.com/meteor/meteor/pull/13522).
Second, there was a silent fail with this piece of code:
```js
.on('finish', async (ver) => {
const property = `versions.${versionName}.meta.gridFsFileId`
await self.collection.updateAsync(file._id, {
$set: {
[property]: ver._id.toHexString(),
},
})
```
`ver` is undefined so it fails to associate the new gridFS instance. Maybe due to internal mongo versions problem. The code had to be modified so the the gridFS id is stored in the return value of openUploadStream
```js
const uploadStream = bucket …
```

Update GridFS exmaple code
